import os

MODEL_ID = "unsloth/whisper-large-v3-turbo"
DATASET_ID = "spktsagar/openslr-nepali-asr-cleaned"
LANGUAGE = "Nepali"
TASK = "transcribe"

MAX_SAMPLES = 500
TEST_SIZE = 0.1

NUM_EPOCHS = 3
BATCH_SIZE = 16
GRAD_ACCUMULATION = 2
LEARNING_RATE = 1e-5
LR_SCHEDULER = "linear"
WARMUP_RATIO = 0.1
WARMUP_STEPS = 500
WEIGHT_DECAY = 0.01

LORA_R = 32
LORA_ALPHA = 64
LORA_DROPOUT = 0.05
USE_RSLORA = True
LORA_TARGET_MODULES = ["q_proj", "v_proj", "k_proj", "out_proj", "fc1", "fc2"]

OUTPUT_DIR = "outputs"
SAVE_STEPS = 6
EVAL_STEPS = 6
SAVE_TOTAL_LIMIT = 3
PATIENCE = 3

MAX_LABEL_LENGTH = 448
SAMPLING_RATE = 16000

LOGGING_STEPS = 1
REPORT_TO = ["tensorboard"]
PREDICT_WITH_GENERATE = True
LOAD_BEST_MODEL_AT_END = True
METRIC_FOR_BEST_MODEL = "wer"
GREATER_IS_BETTER = False